/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_mko_sharedbase64_impl_SharedBase64Impl */

#ifndef _Included_de_mko_sharedbase64_impl_SharedBase64Impl
#define _Included_de_mko_sharedbase64_impl_SharedBase64Impl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_mko_sharedbase64_impl_SharedBase64Impl
 * Method:    _encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_mko_sharedbase64_impl_SharedBase64Impl__1encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_mko_sharedbase64_impl_SharedBase64Impl
 * Method:    _decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_mko_sharedbase64_impl_SharedBase64Impl__1decode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
